frontend/controllers/SettingsController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\filters\AccessControl;

use common\models\AuthConnect;

class SettingsController extends \common\controllers\MyController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
			'connect' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'socialConnectCallback'],
            ]
        ];
    }

    public function actionIndex()
    {
		$model = Yii::$app->user->identity;
		$customer = Yii::$app->user->identity->getCustomer();
		$plan = $customer->getPlan();
		
        return $this->render('index', [
            'model' => $model,
			'customer' => $customer,
			'plan' => $plan,
        ]);
    }	

	/** in-place diting */
    public function actionEditmailpreferences()
    {
		// Check if there is an Editable ajax request
		if (isset($_POST['hasEditable'])) {
			$model = Yii::$app->user->identity;
			// read your posted model attributes			
			$model->attributes = $_POST['User'];
			// read or convert your posted information
			if ($model->save(false)) {				
				$postValues = $_POST[$model->formName()];
				foreach ($postValues as $name => $val) {
					$value = $model->$name;
				}

				// return JSON encoded output in the below format
				echo \yii\helpers\Json::encode(['output'=>$value, 'message'=>'']);
			} else {
			// alternatively you can return a validation error
				echo \yii\helpers\Json::encode(['output'=>'', 'message'=>'Validation error']);
			}
			return;
		}
    }
	
    public function actionSettings()
    {
		$model = Yii::$app->user->identity;
		
		if (Yii::$app->request->post('User') != null) {
			$user = Yii::$app->request->post('User');
			$model->FirstName = $user['FirstName'];
			$model->LastName = $user['LastName'];
			$model->Email = $user['Email'];
			if ($model->save()) {	
				Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Data saved') );
			} else {
				Yii::$app->getSession()->setFlash('error', Yii::t('app', 'Error saving data') );
			}
		}
		
        return $this->render('settings', [
            'model' => $model,
        ]);
    }	


	
    public function actionPassword()
    {
		if (Yii::$app->request->isPost) {
			if (!Yii::$app->user->identity->validatePassword(Yii::$app->request->post('old_password'))) {
				Yii::$app->getSession()->setFlash('error', 'Старата парола е грешна!');			
			}
			else if (!Yii::$app->request->post('new_password') ||
				!Yii::$app->request->post('repeat_password')) {
				Yii::$app->getSession()->setFlash('error', 'Новата парола не може да е празна!');			
			} 
			else if (Yii::$app->request->post('repeat_password') != Yii::$app->request->post('new_password')) {
				Yii::$app->getSession()->setFlash('error', 'Новата парола не съвпада с повтореното въвеждане!');	
			}			
			else if (mb_strlen(Yii::$app->request->post('new_password')) < 4 ) {
				Yii::$app->getSession()->setFlash('error', 'Новата парола не може да е по къса от 4 синвола!');			
			} 
			else {
				Yii::$app->user->identity->setPassword(Yii::$app->request->post('new_password'));				
			}
		}
		
        return $this->render('password');
    }	



    public function actionCompany()
    {
		$model = Yii::$app->user->identity->getCustomer();
		
		if (Yii::$app->request->isPost) {
			if ($model->load(Yii::$app->request->post()) && $model->save()) {
				Yii::$app->getSession()->setFlash('success', 'Data saved');
				return $this->actionIndex();
			} else {
				Yii::$app->getSession()->setFlash('error', 'Error saving data.');
			}
		}
		
        return $this->render('company', [
            'model' => $model,
        ]);
    }	        
    
    
    public function socialConnectCallback($client) {
        $email = $this->getAttrEmail($client);
        
        $found = AuthConnect::findOne(['Email' => $email]);
        if ($found === null) 
        {
            $connect = new AuthConnect();
            $connect->LoginID = Yii::$app->user->identity->LoginID;
            $connect->Email = $email;
            $connect->save(false);
        }
        
        Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Social account connected with {client}', ['client' => $client->getTitle()]));    
        
        return $this->action->redirect( \yii\helpers\Url::to(['settings/index'], true) );
    }	            
}

frontend/views/settings/bg/company.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = Yii::t('app', 'Company details');
$this->params['breadcrumbs'][] = [
            'label' => Yii::t('app', 'Settings'),
            'url' => ['settings/index'],
        ];
$this->params['breadcrumbs'][] = $this->title;

/* @var $this yii\web\View */
/* @var $model common\models\Logins */
/* @var $form ActiveForm */
?>
<div class="settings">

    <?php $form = ActiveForm::begin(['action' => ['settings/company']]); ?>
	
	<?php echo $form->field($model, 'CompanyName')->textInput() ?>
	<?php echo $form->field($model, 'EIK')->textInput() ?>
	<?php echo $form->field($model, 'MOL')->textInput() ?>
	<?php echo $form->field($model, 'Address')->textInput() ?>
	<?php echo $form->field($model, 'IN_DDS')->textInput() ?>
    
	<?= Html::submitButton(Yii::t('app', 'Submit'), ['class' => 'btn btn-primary']) ?>
	<?= Html::a(Yii::t('app', 'Cancel'), ['settings/index']) ?>
	
    <?php ActiveForm::end(); ?>

</div><!-- settings -->

frontend/views/settings/bg/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use kartik\editable\Editable;
use kartik\popover\PopoverX;

$this->title = Yii::t('app','Settings');
$this->params['breadcrumbs'][] = $this->title;

/* @var $this yii\web\View */
/* @var $model common\models\Logins */
/* @var $form ActiveForm */
?>
<span style="font-size: 1.4em; font-weight: bold;"><?= Yii::t('app', 'MentionsSchedule') ?></span>
<?php
	echo Editable::widget([
		'model'=>$model, 
		'inputType' => 'dropDownList',
		'displayValueConfig' => [0 => 'Всеки ден', 
							1 => Yii::t('app', 'Monday'), 
							2 => Yii::t('app', 'Tuesday'),
							3 => Yii::t('app', 'Wednesday'),
							4 => Yii::t('app', 'Thursday'),
							5 => Yii::t('app', 'Friday'),
							6 => Yii::t('app', 'Saturday'),
							7 => Yii::t('app', 'Sundey')],
		'data' => [0 => Yii::t('app', 'Everyday'), 
					1 => Yii::t('app', 'Monday'), 
					2 => Yii::t('app', 'Tuesday'),
					3 => Yii::t('app', 'Wednesday'),
					4 => Yii::t('app', 'Thursday'),
					5 => Yii::t('app', 'Friday'),
					6 => Yii::t('app', 'Saturday'),
					7 => Yii::t('app', 'Sundey')],
		'attribute' => 'MentionsSchedule',
		'size' => 'md',
		'format' => 'link',
		'type' => 'post',
		'editableValueOptions'=>['class'=>'well well-sm'],
		'formOptions' => ['method'=>'post', 'action'=> ['settings/editmailpreferences']]
	]);
?>	
		<?php
			echo PopoverX::widget([
				'header' => Yii::t('app', 'Information'),
				'type' => PopoverX::TYPE_INFO,
				'placement' => PopoverX::ALIGN_RIGHT,
				'content' => 'В кои дни желаете да получавате Email с нови резултати',
				'toggleButton' => ['label'=>'?', 'class'=>'btn btn-info btn-xs'],
			]);	
		?>	

<?= Yii::t('app', 'Mentions by Email') ?>&nbsp;
<?php
	echo Editable::widget([
		'model'=>$model, 
		'inputType' => 'dropDownList',
		'displayValueConfig' => [0 => 'Желая', 
							1 => Yii::t('app', 'Не желая')], 
		'data' => [0 => 'Желая', 
							1 => Yii::t('app', 'Не желая')], 
		'attribute' => 'MentionsNoEmail',
		'size' => 'md',
		'format' => 'link',
		'type' => 'post',
		'editableValueOptions'=>['class'=>'well well-sm'],
		'formOptions' => ['method'=>'post', 'action'=> ['settings/editmailpreferences']]
	]);
?>	
		<?php
			echo PopoverX::widget([
				'header' => Yii::t('app', 'Information'),
				'type' => PopoverX::TYPE_INFO,
				'placement' => PopoverX::ALIGN_RIGHT,
				'content' => 'Ако не желаете да получавате Email известия при нови резултати, изберете - Не желая',
				'toggleButton' => ['label'=>'?', 'class'=>'btn btn-info btn-xs'],
			]);	
		?>	
<br/>

<h2></h2>
<div class="settings">
		<span style="font-size: 1.4em; font-weight: bold;">Лични данни</span>
        <?= $model->Email ?>
    
		<?= Html::a(Yii::t('app', 'Edit'), ['settings/settings' ], ['class' => 'btn btn-info']) ?>
</div> 

<h2></h2>
<div class="settings">
	<span style="font-size: 1.4em; font-weight: bold;"><?php echo Yii::t('app', 'Password') ?></span>
	<?= Html::a(Yii::t('app', 'Edit'), ['settings/password' ], ['class' => 'btn btn-info']) ?>
</div> 

<h2></h2>
<div class="settings">
	<span style="font-size: 1.4em; font-weight: bold;">Данни за фактура</span>

        <?= $customer->CompanyName ?>
		<?= Yii::t('app', 'EIK'); ?>
        <?= $customer->EIK ?>
    
		<?= Html::a(Yii::t('app', 'Edit'), ['settings/company' ], ['class' => 'btn btn-info']) ?>
</div> 

<?php if ($model->IsAdmin && $plan->LoginsCount > 1) { ?>
<h2></h2>
<div class="settings">
	<span style="font-size: 1.4em; font-weight: bold;">Допълнителни потребители</span>
	<?php echo Html::a(Yii::t('app', 'Edit'), ['logins/index' ], ['class' => 'btn btn-info']) ?>
</div> 	
<?php } ?>

frontend/views/settings/bg/password.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Парола';
$this->params['breadcrumbs'][] = [
            'label' => 'Настройки',
            'url' => ['settings/index'],
        ];
$this->params['breadcrumbs'][] = $this->title;

/* @var $this yii\web\View */
/* @var $model common\models\Logins */
/* @var $form ActiveForm */
?>
<div class="settings">

    <?php $form = ActiveForm::begin(); ?>

		<div class="form-group">
		<label style="width: 200px;" for="old_password">Текуща парола</label>
        <?= Html::passwordInput('old_password') ?>
		</div>
		
		<div class="form-group">
		<label style="width: 200px;" for="new_password">Нова парола</label>
		<?= Html::passwordInput('new_password') ?>
		</div>
		
		<div class="form-group">
		<label style="width: 200px;" for="repeat_password">Повторете Новата парола</label>
		<?= Html::passwordInput('repeat_password') ?>
		</div>
    
        <div class="form-group">
		
            <?= Html::submitButton(Yii::t('app', 'Submit'), ['class' => 'btn btn-primary']) ?>
			<?= Html::a(Yii::t('app', 'Cancel'), ['settings/index']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- settings -->

frontend/views/settings/bg/settings.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Лични данни';
$this->params['breadcrumbs'][] = [
            'label' => Yii::t('app', 'Settings'),
            'url' => ['settings/index'],
        ];
$this->params['breadcrumbs'][] = $this->title;

/* @var $this yii\web\View */
/* @var $model common\models\Logins */
/* @var $form ActiveForm */
?>
<div class="settings">

    <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'FirstName') ?>
        <?= $form->field($model, 'LastName') ?>
		<?= $form->field($model, 'Email') ?>
    
        <div class="form-group">
		
            <?= Html::submitButton(Yii::t('app', 'Submit'), ['class' => 'btn btn-primary']) ?>
			<?= Html::a(Yii::t('app', 'Cancel'), ['settings/index']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- settings -->