frontend/controllers/BillingController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
	
use common\controllers\MyController;
use common\models\Customers;
use common\models\Plans;
use common\models\Orders;
use common\models\Words;
use common\models\Invoices;

class BillingController extends MyController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['invoice-external', 'bank-print'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }



    /**
     * Lists all Words models.
     * @return mixed
     */
    public function actionIndex()
    {
		$customer = Yii::$app->user->identity->getCustomer();
		if ($customer->PlanActive < 1) {
			Yii::$app->getSession()->setFlash('warning', Yii::t('app', 'Your Subscription plan has expired'));		
		}

		$plan = Plans::findOne($customer->PlanID);
		$words = Words::find()->where(['CustomerID' => $customer->CustomerID, 'Active' => 1])->count();
	
        $invoiceProvider = new ActiveDataProvider(['query' => Invoices::find()]);
		$invoiceProvider->query->andFilterWhere(['CustomerID' => Yii::$app->user->identity->CustomerID]);		
	
        return $this->render('index', [
            'model' => Yii::$app->user->identity,
			'customer' => $customer,
			'plan' => $plan,
			'words' => $words,
			'invoiceProvider' => $invoiceProvider
        ]);
    }

	
	
    public function actionInvoices()
    {
        $invoiceProvider = new ActiveDataProvider(['query' => Invoices::find()]);
		$invoiceProvider->query->andFilterWhere(['CustomerID' => Yii::$app->user->identity->CustomerID]);		
	
        return $this->render('invoices', [
            'model' => Yii::$app->user->identity,
			'invoiceProvider' => $invoiceProvider
        ]);
    }


	
    public function actionExtend()
    {
		$this->event(Yii::$app->user->identity->CustomerID, EVENT_ORDER_START, 'extend');
		
		$customer = Yii::$app->user->identity->getCustomer();
		
		if ($customer->PlanID == 0) 
		{
			$plan1 = $this->findPlanBySlug('plan1');
			$plan2 = $this->findPlanBySlug('plan2');
			$plan3 = $this->findPlanBySlug('plan3');
			$plan4 = $this->findPlanBySlug('plan4');
		
			return $this->render('plans', [
				'model' => Yii::$app->user->identity,
				'customer' => $customer,
				'plan1' => $plan1,
				'plan2' => $plan2,
				'plan3' => $plan3,
				'plan4' => $plan4,
			]);
		} else {
			// extend existing
			return $this->actionPeriod($customer->PlanID);
		}
    }

	
    public function actionPlan()
    {
		$this->event(Yii::$app->user->identity->CustomerID, EVENT_ORDER_START, 'plan');
	
		$customer = Yii::$app->user->identity->getCustomer();
		
		$plan1 = $this->findPlanBySlug('plan1');
		$plan2 = $this->findPlanBySlug('plan2');
		$plan3 = $this->findPlanBySlug('plan3');
		$plan4 = $this->findPlanBySlug('plan4');
	
		return $this->render('plans', [
			'model' => Yii::$app->user->identity,
			'customer' => $customer,
			'plan1' => $plan1,
			'plan2' => $plan2,
			'plan3' => $plan3,
			'plan4' => $plan4,
		]);
    }


    public function actionPeriod($id)
    {
		$plan = $this->findPlanById($id);	
		$customer = Yii::$app->user->identity->getCustomer();
		
		// on plan change
		$balance = $customer->Balance;
		if ($plan->PlanID != $customer->PlanID) {
			$connection = \Yii::$app->db;
			$model = $connection->createCommand('SELECT datediff(PlanExpirationTime, Now())/30 FROM customers WHERE CustomerID = ' . $customer->CustomerID);
			$months = $model->queryScalar();
		
			$current_plan = $this->findPlanById($customer->PlanID);
			//$balance = $balance + ($months * $plan->
		}
		
        return $this->render('period', [
            'customer' => $customer,
			'balance' => $balance,
			'plan' => $plan,
			'slug' => $plan->slug,
        ]);
    }


	
    public function actionMethod()
    {
		$slug = Yii::$app->request->post('slug');
		$period = Yii::$app->request->post('period');
        return $this->render('method', [
			'period' => $period,
			'slug' => $slug
        ]);
    }

	
	
    public function actionBankStatement()
    {	
		$slug = Yii::$app->request->get('slug');
		$period = Yii::$app->request->get('period');
		
		$plan = $this->findPlanBySlug($slug);			
		$price = $plan->Price;
		if ($period == 3) {
			$price = $plan->Price3m;
		} else if ($period == 6) {
			$price = $plan->Price6m;
		} else if ($period == 12) {
			$price = $plan->Price12m;
		}
		
		$this->event(Yii::$app->user->identity->CustomerID, EVENT_ORDER_END, 'bank:' . $price);
		
		$customer = Yii::$app->user->identity->getCustomer();
		$order = new Orders();
		if ($customer->Balance < $price) {
			$price = $price - $customer->Balance;
			
			$order->BalanceMinus = $customer->Balance;
		} else {
			$order->BalanceMinus = $plan->Price;
		}
				
		// insert into Orders		
		$order->OrderDate = new \yii\db\Expression('NOW()');
		$order->CustomerID = Yii::$app->user->identity->CustomerID;
		$order->PlanID = $plan->PlanID;
		$order->Period = $period;
		$order->Amount = $price;
		$order->MOL = $customer->MOL;
		$order->EIK = $customer->EIK;
		$order->IN_DDS = $customer->IN_DDS;
		$order->Address = $customer->Address;
		$order->CompanyName = $customer->CompanyName;		 
		$order->PaymentMethodID = PAYMENT_METHOD_BANK;
		$order->OrderStatusID = ORDER_PENDING;
				
		if ($order->save()) {
			return $this->render('bank', [
				'order' => $order,
			]);
		} else {
			Yii::$app->getSession()->setFlash('error', implode($order->getFirstErrors(), '<br/>'));
			return $this->actionMethod($slug);
		}	
    }

	
	
	// redirected from ePay on canceled payment
    public function actionEpayCancel()
    {	
		Yii::$app->getSession()->setFlash('error', 'Заявката за плащане бе отказана.');
		return $this->actionIndex();
	}

	
	
	// redirected from ePay on successful payment
    public function actionEpaySuccess()
    {	
		Yii::$app->getSession()->setFlash('info', 'Успешно извършихте плащането. Моля изчакайте няколко минути за да го отрази системата');
		return $this->actionIndex();
	}

	
	
	// redirects to ePay.bg
	// @type := card | login
    public function actionEpayStatement()
    {	
		$slug = Yii::$app->request->get('slug');
		$period = Yii::$app->request->get('period');
		$type = Yii::$app->request->get('type');
		
		$plan = $this->findPlanBySlug($slug);			
		$price = $plan->Price;
		if ($period == 3) {
			$price = $plan->Price3m;
		} else if ($period == 6) {
			$price = $plan->Price6m;
		} else if ($period == 12) {
			$price = $plan->Price12m;
		}

		$this->event(Yii::$app->user->identity->CustomerID, EVENT_ORDER_END, 'epay: ' . $price);
		
		$customer = Yii::$app->user->identity->getCustomer();
		$order = new Orders();
		if ($customer->Balance < $price) {
			$price = $price - $customer->Balance;
			
			$order->BalanceMinus = $customer->Balance;
		} else {
			$order->BalanceMinus = $plan->Price;
		}
				
		// insert into Orders		
		$order->OrderDate = new \yii\db\Expression('NOW()');
		$order->CustomerID = Yii::$app->user->identity->CustomerID;
		$order->PlanID = $plan->PlanID;
		$order->Period = $period;
		$order->Amount = $price;
		$order->MOL = $customer->MOL;
		$order->EIK = $customer->EIK;
		$order->IN_DDS = $customer->IN_DDS;
		$order->Address = $customer->Address;
		$order->CompanyName = $customer->CompanyName;		 
		$order->PaymentMethodID = PAYMENT_METHOD_EPAY;
		$order->OrderStatusID = ORDER_PENDING;
				
		if ($order->save()) {
			return Yii::$app->runAction('epay/post', ['type' => $type,
													'invoiceId' => $order->OrderID, 
													'price' => $price, 
													'description' => 'Абонамент ' . $plan->Name ]);
		} else {
			Yii::$app->getSession()->setFlash('error', implode($order->getFirstErrors(), '<br/>'));
			return $this->actionMethod($slug);
		}	
    }

	
	
    public function actionBankPrint($id)
    {		
		// insert into Orders
		$order = $this->findOrder($id);
		$this->layout = 'blank';
		return $this->render('bankPrint', [
			'order' => $order,
		]);
    }

    public function actionInvoice($id)
    {		
		// data
		$invoice = $this->findInvoice($id);
		$customer = Yii::$app->user->identity->getCustomer();
		//$this->layout = 'blank';
		return $this->render('invoice', [
			'invoice' => $invoice,
			'customer' => $customer,
		]);
    }

    public function actionInvoicePrint($id)
    {		
		// data
		$invoice = $this->findInvoice($id);
		$customer = Yii::$app->user->identity->getCustomer();
		$this->layout = 'blank';
		return $this->render('invoicePrint', [
			'invoice' => $invoice,
			'customer' => $customer,
		]);
    }

	// TODO
    public function actionInvoicePdf($id)
    {		
		// data
		$invoice = $this->findInvoice($id);
		$customer = Yii::$app->user->identity->getCustomer();
		//$this->layout = 'blank';
		
$mpdf=new mPDF('win-1252','A4','','',15,10,16,10,10,10);//A4 page in portrait for landscape add -L.
$mpdf->SetHeader('|Your Header here|');
$mpdf->setFooter('{PAGENO}');// Giving page number to your footer.
$mpdf->useOnlyCoreFonts = true;    // false is default
$mpdf->SetDisplayMode('fullpage');
// Buffer the following html with PHP so we can store it to a variable later
ob_start();
?>
<?php include "phppage.php";
 //This is your php page ?>
<?php 
$html = 		$this->renderPartial('invoice', 
									[
										'invoice' => $invoice,
										'customer' => $customer,
									],
									true);
ob_end_clean();
// send the captured HTML from the output buffer to the mPDF class for processing
$mpdf->WriteHTML($html);
//$mpdf->SetProtection(array(), 'user', 'password'); uncomment to protect your pdf page with password.
$mpdf->Output();
exit;
		

frontend/views/billing/bg/bank.php
<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Банков Превод';
$this->params['breadcrumbs'][] = [
            'label' => Yii::t('app', 'Subscription'),
            'url' => ['billing/index'],
        ];
$this->params['breadcrumbs'][] = $this->title;
?>

<style>
div {
display: block;
overflow: hidden;
width: auto;
}
.platejno {
width: 600px;
margin-bottom: 15px;
}
.platejno div {
width: auto;
zoom: 1;
position: relative;
text-align: left;
}
.platejno_row {
border-left: 2px solid black;
border-right: 2px solid black;
border-top: 2px solid black;
padding: 3px 4px;
}
.platejno_row_title {
font-size: 11px;
padding-bottom: 2px;
}
.platejno_big_title {
font-weight: bold;
}
.platejno_highlight {
background: #C8E8FF;
padding: 0px 4px 2px;
}
.platejno_right {
float: right;
}
.platejno_left {
float: left;
}
.platejno_inp {
border: 1px solid black;
background: url('<?php echo Yii::$app->homeUrl ?>/images/platejno-inp.png') #ffffff 16px 100% repeat-x;
font-family: 'Bitstream Vera Sans Mono', 'Courier New', Courier, monospace;
font-size: 12px;
letter-spacing: 9px;
padding: 10px 0 0 3px;
vertical-align: middle;
width: 585px;
height: 22px;
font-weight: bold;
text-transform: uppercase;
line-height: 10px;
display: inline-block;
}
</style>

<h1><?= Html::encode($this->title) ?></h1>	

<p>
Вашият план ще бъде активиран и ще Ви изпратим Фактура, след като получим плащането ви.
В случай на забавяне или проблем можете да се свържете с нас.
</p>

<b>Данни за банков превод</b>

<p>
Получател: <?php echo \Yii::$app->params['CompanyName'] ?>
<br/>
Банка: <?php echo \Yii::$app->params['BankName'] ?>
<br/>
IBAN: <?php echo \Yii::$app->params['IBAN'] ?>
<br/><br/>
Основание: Абонамент номер <?php echo $order->OrderID ?>
<br/>
Сума: <?php echo $order->Amount ?> лв.
<br/>
</p>

<h3>Патежно нареждане</h3>

<?php $form = ActiveForm::begin(); ?>

<?php echo Html::a(Yii::t('app','Print'), 
				['billing/bank-print', 'id' => $order->OrderID],
				['target' => '_blank']) ?>

<div class="platejno printable">
    <div class="platejno_row">
        <div class="platejno_row_title">Платете на - име на получателя</div>
        <input type="text" class="platejno_inp" size="35" value="ЕРЕПОРТ БЪЛГАРИЯ ЕООД">
    </div>
    <div class="platejno_row" style="padding-left:0; padding-right:0;">
        <div class="platejno_left platejno_highlight" style="_width:365px;">
            <div class="platejno_row_title">IBAN на получателя</div>
            <input type="text" style="width:360px;" class="platejno_inp" size="35" readonly="readonly" value="BG74FINV91501016421151">
        </div>
        <div class="platejno_right platejno_highlight" style="_width:140px;">
            <div class="platejno_row_title">BIC на получателя</div>
            <input type="text" style="width:135px;" class="platejno_inp" size="35" readonly="readonly" value="FINVBGSF">
        </div>
    </div>
    <div class="platejno_row">
        <div class="platejno_row_title">При банка</div>
        <input type="text" class="platejno_inp" size="35" readonly="readonly" value="Първа инвестиционна банка">
    </div>
    <div class="platejno_row" style="padding-right:0;">
        <div class="platejno_left" style="_width:222px;">
            <div class="platejno_big_title">ПРЕВОДНО НАРЕЖДАНЕ</div>
            <div class="platejno_small_title">за кредитен превод</div>
        </div>
        <div class="platejno_right platejno_highlight" style="_width:279px;">
            <div class="platejno_row_title">Сума</div>
            <input type="text" class="platejno_inp" readonly="readonly" style="text-align:right; width: 274px; *width:268px; *padding-right:3px;" size="35" value="<?php echo $order->Amount ?>">
        </div>
        <div class="platejno_right platejno_highlight" style="_width:50px; margin-right: 10px; *margin-right:5px;">
            <div class="platejno_row_title">Валута</div>
            <input type="text" class="platejno_inp" readonly="readonly" style="width:44px;" size="35" value="BGN">
        </div>
    </div>
    <div class="platejno_row">
        <div class="platejno_row_title">Основание за плащане</div>
        <input type="text" class="platejno_inp" readonly="readonly" size="35" value="Абонамент номер <?php echo $order->OrderID ?>">
    </div>
    <div class="platejno_row">
        <div class="platejno_row_title">Още пояснения</div>
        <input type="text" class="platejno_inp" readonly="readonly" size="35" value="www.eReport.bg">
    </div>
    <div class="platejno_row">
        <div class="platejno_row_title">Наредител - име на наредителя</div>
        <input type="text" class="platejno_inp" readonly="readonly" size="35" value="<?php echo $order->CompanyName ?>">
    </div>
    <div class="platejno_row" style="padding-left:0; padding-right:0;">
        <div class="platejno_left platejno_highlight" style="_width:365px;">
            <div class="platejno_row_title">IBAN на наредителя</div>
            <input type="text" class="platejno_inp" readonly="readonly" style="width:360px;" size="35">
        </div>
        <div class="platejno_right platejno_highlight" style="_width:145px;">
            <div class="platejno_row_title">BIC на наредителя</div>
            <input type="text" class="platejno_inp" readonly="readonly" size="35" style="width:140px;">
        </div>
        <div class="platejno_right platejno_highlight" style="margin-right:6px; *margin-right:4px;_width:50px;">
            <div class="platejno_row_title">Валута</div>
            <input type="text" class="platejno_inp" readonly="readonly" size="35" style="width:45px;">
        </div>
    </div>
    <div class="platejno_row" style=" border-bottom:2px solid black;">
        <div class="platejno_left" style="_width:280px;">
            <div class="platejno_row_title">Платежна система:</div>
            <input type="text" class="platejno_inp" readonly="readonly" style="text-align:right; width: 274px;" size="15">
        </div>
        <div class="platejno_right" style="_width:175px;">
            <div class="platejno_row_title">Вальор:</div>
            <input type="text" class="platejno_inp" readonly="readonly" style="width:170px;" size="35" value="">
        </div>
    </div>
</div>

<?php ActiveForm::end(); ?>
	

frontend/views/billing/bg/index.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;

use frontend\widgets\HintWidget;
use kartik\popover\PopoverX;

$this->title = Yii::t('app', 'Subscription');
$this->params['breadcrumbs'][] = $this->title;
?>

<h1><?= Html::encode($this->title) ?></h1>
<div class="settings">

	<table class="table">
	<tr>
		<td>
		<?php echo Yii::t('app', 'Subscription plan') ?>
		</td>
		<td>
		<b><?= $plan->Name ?></b>
		</td>
		<td>
		<?php
			echo PopoverX::widget([
				'header' => Yii::t('app', 'Information'),
				'type' => PopoverX::TYPE_INFO,
				'placement' => PopoverX::ALIGN_RIGHT,
				'content' => Yii::t('app', 'Your current subscription plan'),
				'toggleButton' => ['label'=>'?', 'class'=>'btn btn-info btn-xs'],
			]);	
		?>	
		</td>
		<td>
		<?php echo Html::a(Yii::t('app', 'Extend subscription'), ['billing/extend'], ['class' => 'btn btn-info']) ?>	
		<?php if ($customer->PlanID > 0 && $customer->PlanID < MAX_PLAN_ID) { ?>
		<?php 
			echo Html::a(Yii::t('app', 'Change plan'), ['billing/plan'], ['class' => 'btn btn-success']);
		}
		?>	
		</td>
	</tr>
	<tr>
		<td>
		<?php echo Yii::t('app', 'Next Billing date') ?>
		</td>
		<td>
		<?php $f = new \yii\i18n\Formatter(); echo $f->asDate($customer->PlanExpirationTime); ?>
		<?php if (strtotime($customer->PlanExpirationTime) < time()) { ?>
			<span style="color:red"><?php echo Yii::t('app', 'Expired') ?></span>
		<?php } ?>
		</td>
		<td>
		<?php
			echo PopoverX::widget([
				'header' => Yii::t('app', 'Information'),
				'type' => PopoverX::TYPE_INFO,
				'placement' => PopoverX::ALIGN_RIGHT,
				'content' => Yii::t('app', 'The new plan becomes active after successful order'),
				'toggleButton' => ['label'=>'?', 'class'=>'btn btn-info btn-xs'],
			]);	
		?>
		</td>
	</tr>
	<tr>
		<td>
		<?php echo Yii::t('app', 'Words tracked') ?>
		</td>
		<td>
		<b><?= $words ?>/<?= $plan->WordsCount ?></b>
		(<?php echo \yii\helpers\Html::a(Yii::t('app', 'Details'), ['words/index']) ?>)
		</td>
		<td>
		<?php
			echo PopoverX::widget([
				'header' => Yii::t('app', 'Information'),
				'type' => PopoverX::TYPE_INFO,
				'placement' => PopoverX::ALIGN_RIGHT,
				'content' => Yii::t('app', 'How much of the available words/phrases for tracked you are using'),
				'toggleButton' => ['label'=>'?', 'class'=>'btn btn-info btn-xs'],
			]);	
		?>	
		</td>	
	</tr>
	<?php if (\Yii::$app->language === 'bg-BG') { ?>
	<tr>
		<td>
		Клиентска сметка: 
		</td>
		<td>
		<b><?php echo $customer->Balance ?></b> лв.	
		</td>
		<td>
		<?php
			echo PopoverX::widget([
				'header' => Yii::t('app', 'Information'),
				'type' => PopoverX::TYPE_INFO,
				'placement' => PopoverX::ALIGN_RIGHT,
				'content' => 'Натрупана сума по клиентската Ви сметка. Наличната по клиентската сметка сума може да бъде ползвана за заплащане на всички предлагани от eReport.bg услуги',
				'toggleButton' => ['label'=>'?', 'class'=>'btn btn-info btn-xs'],
			]);	
		?>	
		</td>		
	</tr>
	<?php } ?>
	</table>


</div><!-- settings -->

<h2><?php echo Yii::t('app', 'Issued Invoices') ?></h2>
<?php
echo Html::a(Yii::t('app', 'Issued Invoices Archive'), ['billing/invoices'], ['class' => 'btn btn-info']);
echo '&nbsp;';
echo Html::a(Yii::t('app', 'Company details'), ['settings/company'], ['class' => 'btn btn-info']);
?>

frontend/views/billing/bg/method.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

use kartik\editable\Editable;

$this->title = 'Метод на плащане';
$this->params['breadcrumbs'][] = [
            'label' => Yii::t('app', 'Subscription'),
            'url' => ['billing/index'],
        ];
$this->params['breadcrumbs'][] = $this->title;
 
?>
<style>
.c3col {
  float: left;
  width: 210px;
  height: 180px;
  background: url("<?php echo Yii::$app->homeUrl ?>/images/payBackground.png") no-repeat scroll 0 0 transparent;
  text-align: center;
  margin: 0px 10px 30px 10px;
}
.col_img {
  height: 100px;
  margin-top: 20px; 
}
.col_foot {
height: 60px;
}
</style>

<h1>Метод на плащане</h1>
<div class="settings">

	<div class="c3col">
		<div class="col_img">
			<img src="<?php echo Yii::$app->homeUrl ?>/images/pay-BANK.png" border="0" id="Bank">
		</div>
		<div class="col_foot">
			<a href="<?= Yii::$app->urlManager->createUrl(['billing/bank-statement', 'slug' => $slug, 'period' => $period]) ?>" class="btn btn-info">Банков Превод</a>
		</div>
	</div>
	<div class="c3col">
		<div class="col_img">
			<img src="<?php echo Yii::$app->homeUrl ?>/images/pay-EPAY.png" border="0" id="EPAY">
		</div>
		<div class="col_foot">
			<a href="<?= Yii::$app->urlManager->createUrl(['billing/epay-statement', 'type' => 'login', 'slug' => $slug, 'period' => $period]) ?>" class="btn btn-info">Чрез ePay.bg</a>
		</div>
	</div>
	<div class="c3col">
		<div class="col_img">
			<img src="<?php echo Yii::$app->homeUrl ?>/images/visa-mastercard.gif" border="0" id="EPAY">
		</div>
		<div class="col_foot">
			<a href="<?= Yii::$app->urlManager->createUrl(['billing/epay-statement', 'type' => 'card', 'slug' => $slug, 'period' => $period]) ?>" class="btn btn-info">Кредитна Карта</a>
		</div>
	</div>
	
</div><!-- settings -->

frontend/views/billing/bg/plans.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Logins */
/* @var $form ActiveForm */

$this->title = 'Избор на Абонаментен план';
$this->params['breadcrumbs'][] = [
            'label' => Yii::t('app', 'Subscription'),
            'url' => ['billing/index'],
        ];
$this->params['breadcrumbs'][] = $this->title;
?>
<link rel="stylesheet" href="<?php echo Yii::$app->homeUrl ?>plans-style.css" />
<div class="settings">

    <?php $form = ActiveForm::begin(); ?>
	
  <div class="plans">
	<?php if ($plan4 != null) { ?>
    <div class="plan">
      <h3 class="plan-title"><?php echo $plan4->Name ?></h3>
      <p class="plan-price"><?php echo $plan4->Price ?><span class="plan-unit">лв. на месец</span></p>
      <ul class="plan-features">
        <li class="plan-feature"><?php echo $plan4->WordsCount ?> <span class="plan-feature-name">фрази</span></li>
        <li class="plan-feature"><?php echo $plan4->LoginsCount ?><span class="plan-feature-unit"></span> <span class="plan-feature-name">потребители</span></li>
      </ul>
      <?php 
		if ($customer->PlanID == $plan4->PlanID) {
			echo Html::a(Yii::t('app', 'Extend'), ['billing/extend'], ['class'=>'btn btn-success']);
		} else if ($customer->PlanID < $plan4->PlanID) {
			echo Html::a(Yii::t('app', 'Select'), ['billing/period', 'id' => $plan4->PlanID], ['class'=>'btn btn-info']); 
		} else {
			echo '-';
		}
	  ?>
    </div>
	<?php } ?>
    <div class="plan">
      <h3 class="plan-title"><?php echo $plan3->Name ?></h3>
      <p class="plan-price"><?php echo $plan3->Price ?><span class="plan-unit">лв. на месец</span></p>
      <ul class="plan-features">
        <li class="plan-feature"><?php echo $plan3->WordsCount ?> <span class="plan-feature-name">фрази</span></li>
        <li class="plan-feature"><?php echo $plan3->LoginsCount ?><span class="plan-feature-unit"></span> <span class="plan-feature-name">потребители</span></li>
      </ul>
      <?php 
		if ($customer->PlanID == $plan3->PlanID) {
			echo Html::a(Yii::t('app', 'Extend'), ['billing/extend'], ['class'=>'btn btn-success']);
		} else if ($customer->PlanID < $plan3->PlanID) {
			echo Html::a(Yii::t('app', 'Select'), ['billing/period', 'id' => $plan3->PlanID], ['class'=>'btn btn-info']); 
		} else {
			echo '-';
		}
	  ?>
    </div>
    <div class="plan">
      <h3 class="plan-title"><?php echo $plan2->Name ?></h3>
      <p class="plan-price"><?php echo $plan2->Price ?><span class="plan-unit">лв. на месец</span></p>
      <ul class="plan-features">
        <li class="plan-feature"><?php echo $plan2->WordsCount ?> <span class="plan-feature-name">фрази</span></li>
        <li class="plan-feature"><?php echo $plan2->LoginsCount ?><span class="plan-feature-unit"></span> <span class="plan-feature-name">потребители</span></li>
      </ul>
      <?php 
		if ($customer->PlanID == $plan2->PlanID) {
			echo Html::a(Yii::t('app', 'Extend'), ['billing/extend'], ['class'=>'btn btn-success']);
		} else if ($customer->PlanID < $plan2->PlanID) {
			echo Html::a(Yii::t('app', 'Select'), ['billing/period', 'id' => $plan2->PlanID], ['class'=>'btn btn-info']); 
		} else {
			echo '-';
		}
	  ?>
    </div>
    <div class="plan">
      <h3 class="plan-title"><?php echo $plan1->Name ?></h3>
      <p class="plan-price"><?php echo $plan1->Price ?><span class="plan-unit">лв. на месец</span></p>
      <ul class="plan-features">
        <li class="plan-feature"><?php echo $plan1->WordsCount ?> <span class="plan-feature-name">фрази</span></li>
        <li class="plan-feature"><?php echo $plan1->LoginsCount ?><span class="plan-feature-unit"></span> <span class="plan-feature-name">потребител</span></li>
      </ul>
      <?php 
		if ($customer->PlanID == $plan1->PlanID) {
			echo Html::a(Yii::t('app', 'Extend'), ['billing/extend'], ['class'=>'btn btn-success']);
		} else if ($customer->PlanID < $plan1->PlanID) {
			echo Html::a(Yii::t('app', 'Select'), ['billing/period', 'id' => $plan1->PlanID], ['class'=>'btn btn-info']); 
		} else {
			echo '-';
		}
		?>
    </div>
  </div>
	

    <?php ActiveForm::end(); ?>

</div><!-- settings -->